### PR TITLE
Be able to await until sign in process done completely

### LINKED ISSUE #857: WalletConnection initialisation race condition
**Describe the bug** async method `WalletConnection._completeSignInWithAccessKey` called from constructor cause `keyStore.getKey` to fail to fetch the key

**To Reproduce** after wallet login and return back to `?account_id=test.testnet&public_key=ed25519%..` in the code

const keyStore = new nearApi.keyStores.BrowserLocalStorageKeyStore(); const near = await nearApi.connect(

 {keyStore, ...nearConfig} 

); const walletConnection = new nearApi.WalletConnection(near); const keyPair = await keyStore.getKey(nearConfig.networkId, walletConnection.getAccountId())

keyPair is null

**Expected behavior** keyPair should have a valid key

**Additional context** looks like the reason is: async method `WalletConnection._completeSignInWithAccessKey` called from constructor [https://github.com/near/near-api-js/blob/master/src/wallet-account.ts#L93](https://github.com/near/near-api-js/blob/master/src/wallet-account.ts#L93) might not finish before `keyStore.getKey` tries to fetch the key

### PR DESCRIPTION
**Pull request by aka-toxa**
This should fix https://github.com/near/near-api-js/issues/817 and closes #857 this problem 

also it will help apps understand that keys are ready and can be used after login callback

### CODE REVIEW

**Comment by aka-toxa** [comment]
hey @vgrichina not sure I can do anything to fix the build, it looks like there are some internal issues in the build scripts

**Comment by aka-toxa** [comment]
@MaximusHaximus can you assist with this PR please?

**Comment by aka-toxa** [comment]
Anyone?

**Comment by willemneal** [comment]
@aka-toxa It seems that there is no one tasked with maintaining this package.  They have plans to hire someone, but until then you can expect no PRs to be reviewed.  Thank you for your continued efforts and I hope for your and the ecosystem's sake that they hire someone soon!

**Comment by janewang** [comment]
Reopening this PR.

@esaminu This PR was closed by the stalebot and it addresses a race condition in the contructor. See https://github.com/near/near-api-js/issues/817 Looks a valid issue and could you please review. Thanks

File: src/wallet-account.ts [hunk 1]
```diff
@@ -106,6 +109,25 @@ export class WalletConnection {
...
+     * wallet.isSignedIn(); // true
+     * ```
+     */
+    async promiseSignIn() {
+        if (!this._completeSignInPromise) {
+            return {};
+        }
+
+        return this._completeSignInPromise;
+    }
```
Comment (esaminu) [inline src/wallet-account.ts:129]: Do we need an additional method here? Could we just await the value we assigned the promise to in the constructor? e.g. from test:

```javascript
const newWalletConn = new nearApi.WalletConnection(nearFake, 'promise_on_complete_signin');

await newWalletConn._completeSignInPromise;
expect(await keyStore.getKey('networkId', 'near2.account')).toEqual(keyPair);
...
```

File: src/wallet-account.ts [hunk 2]
```diff
@@ -222,14 +244,15 @@ export class WalletConnection {
...
+            const authData = {
                 accountId,
                 allKeys
             };
-            window.localStorage.setItem(this._authDataKey, JSON.stringify(this._authData));
+            window.localStorage.setItem(this._authDataKey, JSON.stringify(authData));
             if (publicKey) {
                 await this._moveKeyFromTempToPermanent(accountId, publicKey);
             }
+            this._authData = authData;
```
Comment (esaminu) [inline src/wallet-account.ts:255]: Any reason in particular we need to make these changes?

**Review by esaminu — COMMENTED** [review]
Thanks for the PR @aka-toxa ! This is a needed addition. I left a comment regarding how we await

File: src/wallet-account.ts (hunk 1 above)
Comment (zcstarr) [reply src/wallet-account.ts:129]: I don't think you'd want to expose the internals that way. Like if you were to change the impl, you'd be locking people in to that.

File: src/wallet-account.ts [hunk 3]
```diff
@@ -106,6 +109,25 @@ export class WalletConnection {
...
+     * @example
+     * ```js
+     * // on login callback page
+     * const wallet = new WalletConnection(near, 'my-app');
+     * wallet.isSignedIn(); // false
+     * await wallet.promiseSignIn();
+     * wallet.isSignedIn(); // true
+     * ```
+     */
+    async promiseSignIn() {
```
Comment (zcstarr) [inline src/wallet-account.ts:123]: would isSignInComplete or something be a better name? Also just putting 2 cents in as a community member here.

Comment (zcstarr) [reply src/wallet-account.ts:123]: also I'm just a community member that is also hitting this issue :D so 🥳  for this PR

File: src/wallet-account.ts (hunk 1 above)
Comment (esaminu) [reply src/wallet-account.ts:129]: Good point. To address that we can change this to a getter, there's no need for the check and object return

File: src/wallet-account.ts (hunk 3 above)
Comment (zcstarr) [reply src/wallet-account.ts:123]: Actually thinking about this again, it seems like the check for promise should be  contained with isSignedIn(), which seems like you could have an internal variable where the promise is set up if you don't block the execution context and just use a then from the constructor. 🤔

Comment (zcstarr) [reply src/wallet-account.ts:123]: updated it to callbackSignInComplete(). I think it's more descriptive of when this would occur with the connection object, so different context know when they should be blocking for url params to be set in local storage

File: src/wallet-account.ts (hunk 1 above)
Comment (esaminu) [reply src/wallet-account.ts:129]: We want this to be a predicate that resolves to whether sign in was completed on this load of the instance. Therefore the return value should not be the same in both cases. We don't imply failure by returning false if we get the naming right. 

We can actually create a second method here called `isSignedInAsync` to complement the already existing `isSignedIn`:

```javascript
async isSignedInAsync() {
       if (!this._completeSignInPromise) {
           return this.isSignedIn();
       }

       await this._completeSignInPromise;
       return this.isSignedIn();
}
```

File: src/wallet-account.ts (hunk 2 above)
Comment (esaminu) [reply src/wallet-account.ts:255]: The intention here is to only change `this.authData` on the instance once sign in is actually finished and the localStorage changes have completed successfully. Agreed ✅

Comment (esaminu) [reply src/wallet-account.ts:255]: The intention here is to only modify `_authData` on the instance once sign in has _actually_ been completed successfully and the required localStorage changes have been made ✅

**Review by esaminu — APPROVED** [review]
Thanks for the PR @aka-toxa and thanks for the review and brainstorm @zcstarr ! 🎉
