### PR TITLE
fix: get-tx-detail example now uses archival rpc endpoint

### LINKED ISSUE #659: Reference "get-tx-detail" throws error
When trying to run `node get-tx-detail.js` in `examples/transactions` get error:

>UnhandledPromiseRejectionWarning: Error: [-32000] Server error: DB Not Found Error: BLOCK: 8aEcKhF7N1Jyw84e6vHW6Hzp3Ep7mSXJ6Rvnsy5qGJPF

This is probably just not pointing to the archival endpoint and should be. If that's not it, continue work until this example runs with the node command mentioned earlier.

### PR DESCRIPTION
**Pull request by ChaoticTempest**
Fixes #659. Looks to be working after switching over the rpc endpoint:
```
...
working... 9jBCVWg5resUcVgph2YdQXpivDyXCBGq8Cn3m5SxuJbh
working... DZYL6v8ANESE9SoQ4HHkckPSpQk71DGKeaMeVXbJhK81
working... 2XtDDPGiPc9BhiN8ck8efQiWiKonLZgMaaRjDkHwUEHV
working... GZ8vKdcgsavkEndkDWHCjuhyqSR2TGnp9VDZbTzd6ufG
MATCHING TRANSACTIONS:  [
  {
    actions: [ [Object] ],
    hash: '6YRJMXDtZSAZSdZrUnYcuZSfrVKzH1QHeQBBQwUwVjhM',
    nonce: 238411,
    public_key: 'ed25519:4K28jzn9YEzMR2v8J4UQmzbrL6H5kDSqxAKdZaWvQHJt',
    receiver_id: 'client.ropsten.testnet',
    signature: 'ed25519:2evUKBknAcsEvgjxvAcUb8r7iNZMZBkq5mQsJ8hhAwEfnXeyr94vTvWof5XsLkgpA8kdHKjA6UTwaRsCYDG9D2xo',
    signer_id: 'relayer.ropsten.testnet'
  },
  {
    actions: [ [Object], [Object] ],
    hash: 'CJKdeHET5TvTf31cAWpeKNB6uHouSK3FLvfV3RsHSxp4',
    nonce: 238410,
    public_key: 'ed25519:4K28jzn9YEzMR2v8J4UQmzbrL6H5kDSqxAKdZaWvQHJt',
    receiver_id: 'client.ropsten.testnet',
    signature: 'ed25519:EcBjz2MDXRunbH86HA1esVddqQJZXRUEujrgFuaM9RZVPpnQQN2EYvDCAbhrhenH6AGHypMrpjqQU42bDwPmutr',
    signer_id: 'relayer.ropsten.testnet'
  },
  {
    actions: [ [Object] ],
    hash: 'CukbtuCgay4vJv697osi1ep4h1FV2dZ5fUhUPJ1JjaG',
    nonce: 238409,
    public_key: 'ed25519:4K28jzn9YEzMR2v8J4UQmzbrL6H5kDSqxAKdZaWvQHJt',
    receiver_id: 'client.ropsten.testnet',
    signature: 'ed25519:4F9oeNTvZNsM5vjYVjCSnhjK9JRS224GNvuxGWjut9dEagH3PCCDGCDKZ5z6mU6k4buGJ17iy4FxJYAc3Kz6dYGw',
    signer_id: 'relayer.ropsten.testnet'
  },
  {
    actions: [ [Object], [Object] ],
    hash: '2rqBxoUzR8Ks4Yg1CzdbDZZ8DnQ6G7gwcxHqE2W18HcQ',
    nonce: 238408,
    public_key: 'ed25519:4K28jzn9YEzMR2v8J4UQmzbrL6H5kDSqxAKdZaWvQHJt',
    receiver_id: 'client.ropsten.testnet',
    signature: 'ed25519:3SSeiGDcTkhDGaawPnYD7fa7UE2FrRFNBNKeVh4BWEmHS6d9pJaNnH7yiFqZBdVX5kGdcVorEtcZXaQaWZw3HFd2',
    signer_id: 'relayer.ropsten.testnet'
  }
]
TRANSACTION LINKS:  [
  {
    method: 'add_block_header',
    link: 'https://explorer.testnet.near.org/transactions/6YRJMXDtZSAZSdZrUnYcuZSfrVKzH1QHeQBBQwUwVjhM'
  },
  {
    method: 'add_block_header',
    link: 'https://explorer.testnet.near.org/transactions/CJKdeHET5TvTf31cAWpeKNB6uHouSK3FLvfV3RsHSxp4'
  },
  {
    method: 'add_block_header',
    link: 'https://explorer.testnet.near.org/transactions/CukbtuCgay4vJv697osi1ep4h1FV2dZ5fUhUPJ1JjaG'
  },
  {
    method: 'add_block_header',
    link: 'https://explorer.testnet.near.org/transactions/2rqBxoUzR8Ks4Yg1CzdbDZZ8DnQ6G7gwcxHqE2W18HcQ'
  }
]
```

### CODE REVIEW

File: examples/cookbook/transactions/get-tx-detail.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ const keyStore = new keyStores.UnencryptedFileSystemKeyStore(credentialsPath);
 const config = {
   keyStore,
   networkId: "testnet",
-  nodeUrl: "https://rpc.testnet.near.org",
+  nodeUrl: "https://archival-rpc.testnet.near.org",
```
Comment (volovyk-s) [inline examples/cookbook/transactions/get-tx-detail.js:19]: Usually, people do not want to use `archival` nodes. Can we link a note or link to documentation that will describe the difference?

**Review by thisisjoshford — APPROVED** [review]
👍🏼

**Review by volovyk-s — APPROVED** [review]
